### ISSUE TITLE
Auth Token appears to time out

### ISSUE THREAD

**Issue by leacho73** [bigmoby/fglair_for_homeassistant#2]
Hi, 

Firstly, thanks for the awesome integration - everything works as expected, however I find that the authentication token appears to time out before the 86400 seconds?

For example, my Token file was dated 10/06/2022 11:16am and this morning (11/06/2022), my automation to turn on my air con at 6:30am ran, but the unit didn't respond until I restarted Home Assistant and the token was refreshed.

Is there a way to manually refresh the token? Happy to do it on a schedule so that the unit remains connected - I do use the FGLair app also, so not sure if that is re-authenticating me and binning the original token also?

Any help would be great! :)

Thanks
Leacho

**Comment by harrywenjie** [comment]
I too had this problem. I think it's the Fujistu server.  
My HA is on my raspberry pi, so I just put a auto reboot at 4AM in the crontab. 
Everything seems to be working this way.

**Comment by leacho73** [comment]
Ah glad (kinda) its not just me :)

I'm trying to avoid restarting HA every day as I've got a shed load of Node Red flows which would also get reset if I did this - hoping that there is a way to refresh the cookie every couple of hours :)

**Comment by benhumphry** [comment]
Similar problem? 

I have a token file dated 6am this morning, but just a couple of hours later, if I try to switch the HVAC to (for example) 'cool' from 'off' in the integration, it fails (with no explanatory message in the logs). 

Interestingly, in this scenario I can set it to 'auto' or 'heat' without issue, but it refuses to select 'cool' until it has been reloaded. 

Other times, 'auto' is unavailable, while 'cool' can be selected. Sometimes it fails to allow me to select 'off'. 

I wondered whether it was a 'server' or 'hardware' issue, but the FGLAir app seems to function as expected at these times.

I also wondered whether the API was aggressively rate limited, but the problem seems sporadic; sometimes it is days between failure, other times it will happen three or four times in one day.  My automations switch the HVAC between cool and off maybe 3 or 4 times a day.

**Comment by leacho73** [comment]
I'm going to close this issue as I no longer believe this is a token issue, as I've pinpointed this down to a particular unit - whilst all other units in my FGLair app work from home assistant all the time.

New issue opened for this: https://github.com/bigmoby/fglair_for_homeassistant/issues/20
